# Generated by Django 5.2.12 on 2026-03-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='form',
            name='list_of_questions',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
        migrations.AddField(
            model_name='form',
            name='list_of_questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
