import { StyleSheet } from "react-native";
import { Colors } from "./colors";

export const loginStyles = StyleSheet.create({
  safe: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  loaderWrap: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  scrollContent: {
    flexGrow: 1,
    backgroundColor: Colors.background,
  },
  header: {
    height: 260,
    backgroundColor: Colors.headerDark,
    justifyContent: "center",
    alignItems: "center",
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: "hidden",
  },
  headerOverlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: Colors.headerMid,
    opacity: 0.45,
  },
  headerContent: {
    alignItems: "center",
    gap: 10,
  },
  logoBox: {
    width: 68,
    height: 68,
    borderRadius: 18,
    backgroundColor: Colors.accent,
    justifyContent: "center",
    alignItems: "center",
  },
  appName: {
    color: Colors.white,
    fontSize: 34,
    fontWeight: "700",
  },
  appSub: {
    color: Colors.textWhiteMuted,
    fontSize: 14,
  },
  bodyCard: {
    marginTop: -24,
    marginHorizontal: 14,
    backgroundColor: Colors.white,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderRadius: 22,
    paddingHorizontal: 20,
    paddingTop: 30,
    paddingBottom: 26,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
  },
  bodyTitle: {
    fontSize: 32,
    fontWeight: "700",
    color: Colors.textPrimary,
    marginBottom: 4,
  },
  bodySub: {
    fontSize: 14,
    color: Colors.textSecondary,
    marginBottom: 24,
  },
  label: {
    fontSize: 16,
    fontWeight: "600",
    color: Colors.textPrimary,
    marginBottom: 8,
  },
  input: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    color: Colors.textPrimary,
    marginBottom: 14,
    fontSize: 16,
  },
  passwordWrap: {
    height: 52,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: Colors.cardBorder,
    backgroundColor: Colors.background,
    paddingHorizontal: 14,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  passwordWrapError: {
    borderColor: "#EF4444",
    backgroundColor: "#FFF5F5",
  },
  passwordInput: {
    flex: 1,
    color: Colors.textPrimary,
    fontSize: 16,
    marginRight: 8,
  },
  errorText: {
    marginTop: -6,
    marginBottom: 8,
    color: "#EF4444",
    fontSize: 12,
    fontWeight: "600",
  },
  domainHint: {
    fontSize: 13,
    color: Colors.accent,
    textAlign: "right",
    marginBottom: 14,
    fontWeight: "600",
  },
  primaryButton: {
    height: 54,
    borderRadius: 16,
    backgroundColor: Colors.headerDark,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 14,
  },
  buttonDisabled: {
    opacity: 0.65,
  },
  primaryButtonText: {
    color: Colors.white,
    fontWeight: "700",
    fontSize: 17,
  },
  secondaryButton: {
    height: 54,
    borderRadius: 16,
    borderWidth: 2,
    borderColor: Colors.headerDark,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.white,
  },
  secondaryButtonText: {
    color: Colors.headerDark,
    fontWeight: "600",
    fontSize: 15,
  },
});
