# Generated by Django 6.0.2 on 2026-03-04 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=50)),
                ('schema', models.JSONField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diligenciamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado')], default='borrador', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formats.formatotecnico')),
            ],
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_id', models.CharField(max_length=100)),
                ('archivo', models.ImageField(upload_to='adjuntos/')),
                ('diligenciamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjuntos', to='formats.diligenciamiento')),
            ],
        ),
    ]
