# Generated by Django 5.2.12 on 2026-03-15 00:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diligenciamiento',
            name='formato',
        ),
        migrations.RemoveField(
            model_name='diligenciamiento',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='formatotecnico',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='FormularioInstancia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField()),
                ('estado', models.CharField(choices=[('BORRADOR', 'BORRADOR'), ('ENVIADO', 'ENVIADO')], default='BORRADOR', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('formato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formats.formatotecnico')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Adjunto',
        ),
        migrations.DeleteModel(
            name='Diligenciamiento',
        ),
    ]
