# Generated by Django 6.0 on 2026-03-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0002_remove_diligenciamiento_formato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatotecnico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='formularioinstancia',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
