# Generated by Django 6.0 on 2026-04-19 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0003_alter_formatotecnico_id_alter_formularioinstancia_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenFormulario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='formularios/imagenes/%Y/%m/')),
                ('nombre_original', models.CharField(max_length=255)),
                ('tamano', models.PositiveIntegerField(help_text='Tamaño en bytes')),
                ('subida_en', models.DateTimeField(auto_now_add=True)),
                ('instancia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='formats.formularioinstancia')),
            ],
            options={
                'ordering': ['-subida_en'],
            },
        ),
    ]
