# Generated by Django 6.0.4 on 2026-04-24 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0004_imagenformulario'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinstancia',
            name='nombre_personalizado',
            field=models.CharField(blank=True, help_text='Nombre personalizado que el usuario le da a esta instancia (ej: Torre 4 - Eje B)', max_length=255, null=True),
        ),
    ]
