# Generated by Django 4.2.30 on 2026-05-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formats', '0005_formularioinstancia_nombre_personalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='formularioinstancia',
            name='archivado',
            field=models.BooleanField(default=False, help_text='Marcado por un Socio para ocultar del listado principal'),
        ),
    ]
